name: Release

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build and push docker images

    env:
      VERSION: "0.0"

    steps:
    
    - name: Informing
      run: echo "Trigger '${{ github.event_name }}', branch '${{ github.ref }}', named '${{ github.ref_name }}'"

    - name: Set version
      run: |
        echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Checking out repository
      uses: actions/checkout@v2

    - name: Get version
      run: |
       echo $VERSION

    - name: Build docker image
      run: |
       docker build --pull --build-arg VERSION=$VERSION --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg BUILD_NUMBER=$GITHUB_RUN_NUMBER --tag 61850-sim:$GITHUB_RUN_NUMBER .
    
    - name: Tag docker images
      run: |
       docker tag 61850-sim:$GITHUB_RUN_NUMBER stinging/61850-sim
       docker tag 61850-sim:$GITHUB_RUN_NUMBER stinging/61850-sim:$VERSION
       docker tag 61850-sim:$GITHUB_RUN_NUMBER harbor.sting.dev/library/61850-sim
       docker tag 61850-sim:$GITHUB_RUN_NUMBER harbor.sting.dev/library/61850-sim:$VERSION
   
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker images to DockerHub
      run: |
       docker push stinging/61850-sim
       docker push stinging/61850-sim:$VERSION

    - name: Login to StingHarbor
      uses: docker/login-action@v1
      with:
        registry: harbor.sting.dev
        username: ${{ secrets.STINGHARBOR_USERNAME }}
        password: ${{ secrets.STINGHARBOR_PASSWORD }}

    - name: Push docker images to StingHarbor
      run: |
       docker push harbor.sting.dev/library/61850-sim
       docker push harbor.sting.dev/library/61850-sim:$VERSION

